version: "3.2"

services:
  api-gateway:
    image: itl-teams/api-gateway:latest
    build: ./api
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "80:80"

  user-credentials:
    image: itl-teams/user-credentials:latest
    build: ./services/user-credentials
    container_name: user-credentials
    restart: unless-stopped
    environment:
      - APP_NAME=User Credentials
      - PORT=80
    env_file:
      - ".env"
    volumes:
      - ./services/user-credentials/src:/home/app/src

  account-and-signature:
    container_name: account-and-signature
    restart: unless-stopped
    image: itl-teams/php:latest
    build: ./services/account-and-signature
    env_file:
      - ".env"
    volumes:
      - ./services/account-and-signature/public:/var/www/html
      - ./services/account-and-signature/app:/var/www/app

  company-budgets:
    container_name: company-budgets
    restart: unless-stopped
    image: itl-teams/php:latest
    build: ./services/company-budgets
    env_file:
      - ".env"
    volumes:
      - ./services/company-budgets/public:/var/www/html
      - ./services/company-budgets/app:/var/www/app

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - ./services/mysql:/docker-entrypoint-initdb.d
    env_file:
      - ".env"

  agreement:
    image: itl-teams/agreement:dev
    build: ./services/agreement
    container_name: agreement
    restart: unless-stopped
    environment:
      - APP_NAME=Agreement/Express App
      - DEV_PORT=3000
    env_file:
      - ".env"
    volumes:
      - ./services/agreement/src:/home/app/src
